config/routes.rb
Rails.application.routes.draw do
  resources :products_lots do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
      get 'lote_by_product/:product_id' => 'products_lots#lote_by_product', as: :lote_by_product
      get 'empty_lots/:product_id' => 'products_lots#empty_lots', as: :empty_lots
    end
  end

  resources :businesses

  resources :drivers

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'main#index'
  get 'inbox_task' => 'main#inbox_task', as: :inbox_task_main
  get 'home' => 'main#home'
  post 'home' => 'main#home'

  resources :clients
  resources :drivers
  resources :categories
  resources :suppliers
  resources :products
  resources :transports
  resources :stock_for_articles do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
    end
  end
  resources :contracts do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :remission_guides do
    collection do
      post 'add_item'
    end
  end
  resources :purchase_orders do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :vouchers do
    collection do
      post 'add_item'
    end
  end

end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_one :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :client
  has_many :contract_details
  has_many :contract_documents
  accepts_nested_attributes_for :contract_details, :allow_destroy => true
  accepts_nested_attributes_for :contract_documents, :allow_destroy => true
end

app/models/contract_detail.rb
class ContractDetail < ActiveRecord::Base
  belongs_to :contract
  belongs_to :article
end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_one :products_lot
end

app/models/products_lot.rb
class ProductsLot < ActiveRecord::Base
	belongs_to :product
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
  has_many :purchase_order_details
  has_many :purchase_order_documents
  accepts_nested_attributes_for :purchase_order_details, :allow_destroy => true
  accepts_nested_attributes_for :purchase_order_documents, :allow_destroy => true
end

app/models/remission_guide.rb
class RemissionGuide < ActiveRecord::Base
  belongs_to :client
  has_many :remission_guide_details
  accepts_nested_attributes_for :remission_guide_details, :allow_destroy => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :client
  has_many :voucher_details
  accepts_nested_attributes_for :voucher_details, :allow_destroy => true
end

app/models/voucher_detail.rb
class VoucherDetail < ActiveRecord::Base
  belongs_to :voucher
  belongs_to :article
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new, :create, :edit, :update ]
  protect_from_forgery with: :null_session, :only => [:destroy, :delete]
  def index
    @transport = Transport.all
    render layout: false
  end

  def show
    @transport = Transport.find(params[:id])
    render layout: false
  end

  def new
    @transport = Transport.new 
    @today = Time.now
    render layout: false
  end

  def create
    flash[:error] = nil
    transport = Transport.new(transport_parameters)
    if transport.save
      flash[:notice] = "Se ha creado correctamente."
      redirect_to :action => :index
    else
      transport.errors.messages.each do |attribute, error|
        puts flash[:error].to_s + error.to_s + "  "
      end
      @transport = transport
      render :new, layout: false 
    end
  end

  def edit
    @transport = Transport.find(params[:id])
    @action = 'edit'
    render layout: false
  end

  def update
    flash[:error] = nil
    transport = Transport.find(params[:id])
    if transport.update_attributes(transport_parameters)
      flash[:notice] = "Se ha actualizado correctamente los datos."
      redirect_to :action => :index
    else
      transport.errors.messages.each do |attribute, error|
        flash[:error] =  flash[:error].to_s + error.to_s + "  "
      end
      @transport = transport
      render :edit, layout: false
    end
  end

  def destroy
    transport = Transport.destroy(params[:id])
    flash[:notice] = "Se ha eliminado correctamente."
    render :json => transport
  end
  
  private
  def transport_parameters
    params.require(:transport).permit(:plate,:trademark)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/transports/_form.haml
#wid-id-0.jarviswidget{"data-widget-colorbutton" => "false", "data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-eye
    %h2 Unidad de Transporte
  .widget-body
    = simple_form_for([@transport], html: {class: 'form-horizontal smart-form', autocomplete: 'off' }) do |f|
      %fieldset
        .row
          %section.col.col-10
            %label.label Placa
            %label.input{for: "name"}
              = f.input :plate, placeholder: "Placa", input_html: { class: 'form-control' }, label: false
        .row
          %section.col.col-10
            %label.label Marca/Modelo
            %label.input{for: "code"}
              = f.input :trademark, placeholder: "Marca Modelo", input_html: { class: 'form-control' }, label: false
      %footer
        %button.btn.btn-primary{type: "submit"}
          %i.fa.fa-save
            Guardar

:javascript
  $(document).ready(function () {
    if($('form[id^="edit_"]').length > 0) {
      submit_validate($('form[id^="edit_"]'));
    }else{
      submit_validate($('#new_transport'));
    }
  });

  function submit_validate(form){
    $(form['selector']).ajaxForm({
      beforeSubmit: function() {
        $(form['selector']).validate({
          // Rules for form validation
          rules : {
            'article[name]' : {
              required : true
            },
            'article[ruc]' : {
              digits : true,
              minlength : 8,
              maxlength : 11
            }
          },

          // Messages for form validation
          messages : {
            'article[name]' : {
              required : 'Por favor, ingresar el nombre o razon social.'
             },
            'article[ruc]' : {
              digits : 'Por favor, ingresar solo dígitos.',
              maxlength: 'Debe ser 8 u 11 digitos',
              minlength: 'Debe ser 8 u 11 dígitos'
             }
          },

          // Do not change code below
          errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
          }
        });
        // Remove all Help-inLine
        $(".help-inline").remove();
        // Client Valid
        return $(form['selector']).valid();
      },
      target: '#content',
      success: function (data){
        $(".help-inline").parent().addClass("state-error");
      },
      error: function(xhr, status, error) {
      }
    });
  }

app/views/transports/_table.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2 Unidades de Transporte
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th #
            %th Placa
            %th Marca/Modelo
            %th Acciones
        %tbody
          - @transport.each do |unit|
            %tr
              %td 
                = unit.id
              %td 
                = unit.plate
              %td 
                = unit.trademark
              %td
                %a.btn.btn-warning.btn-xs{:onclick => "javascript:load_url_ajax('#{edit_transport_path(unit.id)}', 'content', null, null, 'GET')"}
                  Editar
                %a.btn.btn-danger.btn-xs{:data => {:toggle => 'confirmation', :placement => 'left', :title => 'Esta seguro de eliminar el item ' + "#{unit.id}?", :singleton => 'true', :popout => 'true', :onclick => "javascript:delete_to_url('#{transport_path(unit.id)}' + '?authenticity_token=#{form_authenticity_token}', 'content', '#{transports_path}')"}}
                  Eliminar

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

  // PAGE RELATED SCRIPTS

  loadDataTableScripts();
  function loadDataTableScripts() {

    loadScript("#{ asset_path 'plugin/datatables/jquery.dataTables-cust.min', type: :javascript }", dt_2);

    function dt_2() {
      loadScript("#{ asset_path 'plugin/datatables/ColReorder.min', type: :javascript }", dt_3);
    }

    function dt_3() {
      loadScript("#{ asset_path 'plugin/datatables/FixedColumns.min.js', type: :javascript }", dt_4);
    }

    function dt_4() {
      loadScript("#{ asset_path 'plugin/datatables/ColVis.min', type: :javascript }", dt_5);
    }

    function dt_5() {
      loadScript("#{ asset_path 'plugin/datatables/ZeroClipboard', type: :javascript }", dt_6);
    }

    function dt_6() {
      loadScript("#{ asset_path 'plugin/datatables/media/js/TableTools.min', type: :javascript }", dt_7);
    }

    function dt_7() {
      loadScript("#{ asset_path 'plugin/datatables/DT_bootstrap', type: :javascript }", runDataTables);
    }

  }

  function runDataTables() {

    /*
     * BASIC
     */
    $('#dt_basic').dataTable({
      "sPaginationType" : "bootstrap_full"
    });

    /* END BASIC */

    /* Add the events etc before DataTables hides a column */
    $("#dt_basic thead input").keyup(function() {
      oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
    });

    $("#dt_basic thead input").each(function(i) {
      this.initVal = this.value;
    });
    $("#datatable_fixed_column thead input").focus(function() {
      if (this.className == "search_init") {
        this.className = "";
        this.value = "";
      }
    });
    $("#dt_basic thead input").blur(function(i) {
      if (this.value == "") {
        this.className = "search_init";
        this.value = this.initVal;
      }
    });   
    

    var oTable = $('#datatable_fixed_column').dataTable({
      "sDom" : "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
      "oLanguage" : {
        "sSearch" : "Search all columns:"
      },
      "bSortCellsTop" : true
    });   
    


    /*
     * COL ORDER
     */
    $('#datatable_col_reorder').dataTable({
      "sPaginationType" : "bootstrap",
      "sDom" : "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "fnInitComplete" : function(oSettings, json) {
        $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
      }
    });
    
    /* END COL ORDER */

    /* TABLE TOOLS */
    $('#datatable_tabletools').dataTable({
      "sDom" : "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "oTableTools" : {
        "aButtons" : ["copy", "print", {
          "sExtends" : "collection",
          "sButtonText" : 'Save <span class="caret" />',
          "aButtons" : ["csv", "xls", "pdf"]
        }],
        "sSwfPath" : "#{ asset_path 'javascript/plugin/datatables/media/swf/copy_csv_xls_pdf.swf'}"
      },
      "fnInitComplete" : function(oSettings, json) {
        $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function() {
          $(this).addClass('btn-sm btn-default');
        });
      }
    });
    
    /* END TABLE TOOLS */

  }

app/views/transports/edit.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Editar
  #widget-grid
    .row
      %article.col-sm-12.col-md-12.col-lg-6
        = render :partial => 'form'
        
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left>
    Retornar al listado

:javascript
  $('#backlist-entity').click(function(){
    load_url_ajax("#{transports_path}", 'content', null, null, 'GET');
  });

app/views/transports/index.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h2.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Lista de Unidades de Transporte
      - if flash[:notice] !=nil
        .alert.alert-success.fade.in{"style" => "clear:both"}
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Exito
          = flash[:notice]
      - if flash[:error] != nil
        .alert.alert-danger.fade.in
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Error!
          = flash[:error]
  .row
    .col-sm-4
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{new_transport_path}', 'content', null, null, 'GET')"}
        Agregar Transporte

  %br
  .row
    #widget-grid 
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        = render :partial => 'table'

app/views/transports/new.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Nuevo Transporte
  #widget-grid
    .row
      %article.col-sm-12.col-md-12.col-lg-8
        = render :partial => 'form'
        
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left>
    Retornar al listado

:javascript
  $('#backlist-entity').click(function(){
    load_url_ajax("#{transports_path}", 'content', null, null, 'GET');
  });