config/routes.rb
Rails.application.routes.draw do
  resources :products_lots do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
      get 'lote_by_product/:product_id' => 'products_lots#lote_by_product', as: :lote_by_product
      get 'empty_lots/:product_id' => 'products_lots#empty_lots', as: :empty_lots
    end
  end

  resources :businesses

  resources :drivers

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'main#index'
  get 'inbox_task' => 'main#inbox_task', as: :inbox_task_main
  get 'home' => 'main#home'
  post 'home' => 'main#home'

  resources :clients
  resources :drivers
  resources :categories
  resources :suppliers
  resources :products
  resources :transports
  resources :stock_for_articles do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
    end
  end
  resources :contracts do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :remission_guides do
    collection do
      post 'add_item'
    end
  end
  resources :purchase_orders do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :vouchers do
    collection do
      post 'add_item'
    end
  end

end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_one :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :client
  has_many :contract_details
  has_many :contract_documents
  accepts_nested_attributes_for :contract_details, :allow_destroy => true
  accepts_nested_attributes_for :contract_documents, :allow_destroy => true
end

app/models/contract_detail.rb
class ContractDetail < ActiveRecord::Base
  belongs_to :contract
  belongs_to :article
end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_one :products_lot
end

app/models/products_lot.rb
class ProductsLot < ActiveRecord::Base
	belongs_to :product
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
  has_many :purchase_order_details
  has_many :purchase_order_documents
  accepts_nested_attributes_for :purchase_order_details, :allow_destroy => true
  accepts_nested_attributes_for :purchase_order_documents, :allow_destroy => true
end

app/models/remission_guide.rb
class RemissionGuide < ActiveRecord::Base
  belongs_to :client
  has_many :remission_guide_details
  accepts_nested_attributes_for :remission_guide_details, :allow_destroy => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :client
  has_many :voucher_details
  accepts_nested_attributes_for :voucher_details, :allow_destroy => true
end

app/models/voucher_detail.rb
class VoucherDetail < ActiveRecord::Base
  belongs_to :voucher
  belongs_to :article
end

app/controllers/products_lots_controller.rb
class ProductsLotsController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new, :create, :edit, :update ]
  protect_from_forgery with: :null_session, :only => [:destroy, :delete]

  def index
    @products_lot =  ProductsLot.select("product_id, sum(quantity) as quantity").group("product_id")
    render layout: false
  end

  def show
    @products_lot = ProductsLot.find(params[:id])
    render layout: false
  end

  def new
    @products_lot = ProductsLot.new
    @products = Product.all
    @today = Time.now
    render layout: false
  end

  def create
    flash[:error] = nil
    products_lot = ProductsLot.new(products_lot_params)
    if products_lot.save
      flash[:notice] = "Se ha creado correctamente."
      redirect_to :action => :index
    else
      products_lot.errors.messages.each do |attribute, error|
        puts flash[:error].to_s + error.to_s + "  "
      end
      @products_lot = products_lot
      render :new, layout: false 
    end
  end

  def edit
    @products_lot = ProductsLot.find(params[:id])
    @products = Product.all
    @action = 'edit'
    render layout: false
  end

  def update
    flash[:error] = nil
    products_lot = ProductsLot.find(params[:id])
    if products_lot.update_attributes(products_lot_params)
      flash[:notice] = "Se ha actualizado correctamente los datos."
      redirect_to :action => :index
    else
      products_lot.errors.messages.each do |attribute, error|
        flash[:error] =  flash[:error].to_s + error.to_s + "  "
      end
       @products_lot = products_lot
      render :edit, layout: false
    end
  end

  def destroy
    products_lot = ProductsLot.destroy(params[:id])
    flash[:notice] = "Se ha eliminado correctamente el lote seleccionado."
    render :json => products_lot
  end
  
  def due_front
    render(partial: 'due_front', :layout => false)
  end

  def due_method
    limit_date = params[:end_date]
    @products_lots = ProductsLot.where("due_date <= ?",limit_date)
    render(partial: 'report_due_table', :layout => false)
  end

  def lote_front
    @products = Product.all
    render(partial: 'lote_front', :layout => false)
  end
  def lote_by_product
    product_id = params[:product_id]
    @products_lots = ProductsLot.where("product_id = ? and quantity > 0",product_id)
    render(partial: 'lote_by_product', :layout => false)
  end
  def lote_method
    product_id = params[:product_id]
    @products_lots = ProductsLot.where("product_id = ?",product_id)
    render(partial: 'report_lote_table', :layout => false)
  end
  def empty_lots
    product_id = params[:product_id]
    @products_lots = ProductsLot.where("product_id = ? and quantity = 0",product_id)
    render(partial: 'lote_by_product', :layout => false)
  end

  private
    def products_lot_params
      params.require(:products_lot).permit(:quantity, :sanitary_registry, :due_date, :lot_number, :production_date, :product_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/products_lots/_due_front.haml
#content-inside
  .row
    .col-md-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Lotes de Productos por Vencer

  .row
    .col-md-12.well
      .input-group
        .col-md-14
          .col-md-10
            %label Fecha de Vencimiento
            %input#enddate.string.optional.form-control{'name'=>'end_date', type: "date"}
          %br
          .col-md-2
            %button#show-table.btn.btn-primary.btn-default{:type => 'button'}
              %i.fa.fa-search
              Buscar
  %br
  .row
    #widget-grid
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        #table-information-result
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left
    Retornar al listado

:javascript
  $(document).ready(function (){
    $('select').select2({width:'280px'});
  });

  $('#show-table').click(function(){
    var end_date = $('#enddate').val();

    if(end_date != 0) {
      var parameters = { end_date: end_date, authenticity_token: "#{form_authenticity_token}" };
      load_items_delivery_order_ajax("#{due_method_products_lots_path}", 'table-information-result', parameters);
    } else {
      alert('Por favor, especificar todos los datos necesarios.')
    }
  });


  $('#backlist-entity').click(function(){
    load_url_ajax("#{products_lots_path}", 'content', null, null, 'GET');
  });

app/views/products_lots/_form.html.haml
#wid-id-0.jarviswidget{"data-widget-colorbutton" => "false", "data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-eye
    %h2 Lote de Producto
  .widget-body
    = simple_form_for([@products_lot], html: {class: 'form-horizontal smart-form', autocomplete: 'off' }) do |f|
      %fieldset
        .row
          %section.col.col-md-5
            %label.label Producto
            %select.form-control#product-select{:name =>"products_lot[product_id]", :required => true}
              %option{:value => "", :rel => ""}
                Seleccione
              - @products.each do |x|
                %option{:value => "#{x.id}"}
                  = x.name.to_s
          %section.col.col-md-5
            %label.label Cantidad
            %label.input{for: "quantity"}
              = f.number_field :quantity, placeholder: "0", input_html: { class: 'form-control' }, label: false
        .row
          %section.col.col-md-5
            %label.label Número de Lote
            %label.input{for: "lot_number"}
              = f.text_field :lot_number, placeholder: "Número de Lote", input_html: { class: 'form-control' }, label: false
          %section.col.col-md-5
            %label.label Registro Sanitario
            %label.input{for: "sanitary_registry"}
              = f.text_field :sanitary_registry, placeholder: "Registro Sanitario", input_html: { class: 'form-control' }, label: false
        .row
          %section.col.col-md-5
            %label.label Fecha de Producción
            %label.input{for: "production_date"}
              = f.date_field :production_date, input_html: { class: 'form-control' }, label: false
          %section.col.col-md-5
            %label.label Fecha de Vencimiento
            %label.input{for: "due_date"}
              = f.date_field :due_date, input_html: { class: 'form-control' }, label: false 
      %footer
        %button.btn.btn-primary{type: "submit"}
          %i.fa.fa-save
            Guardar

:javascript
  
  $(document).ready(function () {
    if($('form[id^="edit_"]').length > 0) {
      submit_validate($('form[id^="edit_"]')); 
      id = "#{ @products_lot.product_id.to_json }"; 
      $('#product-select option[value="'+id+'"]').prop('selected', 'selected')
    }else{
      submit_validate($('#new_products_lot'));
    }
  });

  function submit_validate(form){
    $(form['selector']).ajaxForm({
      beforeSubmit: function() {
        $(form['selector']).validate({
          // Rules for form validation
          rules : {
            'products_lot[product_id]' : {
              required : true
            },
            'products_lot[quantity]' : {
              required : true
            },
            'products_lot[due_date]'  : {  
              required : true,
            }
          },

          // Messages for form validation
          messages : {
            'product[name]' : {
              required : 'Por favor, ingresar el nombre o razon social.'
             },
            'product[unit_of_measurement]' : {
              required : 'Por favor, ingresar la unidad de medida.'
             },
            'product[quantity]' : {
              required : 'Por favor, ingresar la cantidad.'
             }
          },

          // Do not change code below
          errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
          }
        });
        // Remove all Help-inLine
        $(".help-inline").remove();
        // Client Valid
        return $(form['selector']).valid();
      },
      target: '#content',
      success: function (data){
        $(".help-inline").parent().addClass("state-error");
      },
      error: function(xhr, status, error) {
      }
    });
  }

app/views/products_lots/_lote_by_product.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Lotes por Producto
  %br
  .row
    #widget-grid 
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        = render :partial => 'report_lote_by_product'
        
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left>
    Retornar al listado

:javascript
  $('#backlist-entity').click(function(){
    load_url_ajax("#{products_lots_path}", 'content', null, null, 'GET');
  });

app/views/products_lots/_lote_front.haml
#content-inside
  .row
    .col-md-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Lotes por Producto

  .row
    .col-md-12.well
      .input-group
        .col-md-14
          .col-md-10
            .row{ :style => "margin-top:5%;"}
              %section.col.col-md-12
                %select.form-control#product-select{:name =>"product_id", :required => false}
                  %option{:value => "", :rel => ""}
                    Seleccione
                  - @products.each do |x|
                    %option{:value => "#{x.id}"}
                      = x.name.to_s
          %br
          .col-md-2
            %button#show-table.btn.btn-primary.btn-default{:type => 'button'}
              %i.fa.fa-search
              Buscar
  %br
  .row
    #widget-grid
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        #table-information-result
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left
    Retornar al listado

:javascript
  $(document).ready(function (){
    $('select').select2({width:'280px'});
  });

  $('#show-table').click(function(){
    var product = $('#product-select').val();

    if(product != 0) {
      var parameters = { product_id: product, authenticity_token: "#{form_authenticity_token}" };
      load_items_delivery_order_ajax("#{lote_method_products_lots_path}", 'table-information-result', parameters);
    } else {
      alert('Por favor, especificar todos los datos necesarios.')
    }
  });


  $('#backlist-entity').click(function(){
    load_url_ajax("#{products_lots_path}", 'content', null, null, 'GET');
  });

app/views/products_lots/_report_lote_by_product.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2 Lotes por Producto
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Producto
            %th Cantidad
            %th Registro Sanitario
            %th Número de Lote
            %th Fecha de Vencimiento
            %th Fecha de Producción
            %th Acciones
        %tbody
          - @products_lots.each do |unit|
            %tr
              %td
                = Product.find(unit.product_id).name
              %td
                = unit.quantity.to_s
              %td
                = unit.sanitary_registry.to_s
              %td
                = unit.lot_number.to_s
              %td
                = unit.due_date.to_s
              %td
                = unit.production_date.to_s
              %td
                %a.btn.btn-warning.btn-xs{:onclick => "javascript:load_url_ajax('#{edit_products_lot_path(unit.id)}', 'content', null, null, 'GET')"}
                  Editar
                %a.btn.btn-danger.btn-xs{:data => {:toggle => 'confirmation', :placement => 'left', :title => 'Esta seguro de eliminar el item ' + "#{unit.id}?", :singleton => 'true', :popout => 'true', :onclick => "javascript:delete_to_url('#{products_lot_path(unit.id)}' + '?authenticity_token=#{form_authenticity_token}', 'content', '#{products_lots_path}')"}}
                  Eliminar

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

  // PAGE RELATED SCRIPTS

  loadDataTableScripts();
  function loadDataTableScripts() {

    loadScript("#{ asset_path 'plugin/datatables/jquery.dataTables-cust.min', type: :javascript }", dt_2);

    function dt_2() {
      loadScript("#{ asset_path 'plugin/datatables/ColReorder.min', type: :javascript }", dt_3);
    }

    function dt_3() {
      loadScript("#{ asset_path 'plugin/datatables/FixedColumns.min.js', type: :javascript }", dt_4);
    }

    function dt_4() {
      loadScript("#{ asset_path 'plugin/datatables/ColVis.min', type: :javascript }", dt_5);
    }

    function dt_5() {
      loadScript("#{ asset_path 'plugin/datatables/ZeroClipboard', type: :javascript }", dt_6);
    }

    function dt_6() {
      loadScript("#{ asset_path 'plugin/datatables/media/js/TableTools.min', type: :javascript }", dt_7);
    }

    function dt_7() {
      loadScript("#{ asset_path 'plugin/datatables/DT_bootstrap', type: :javascript }", runDataTables);
    }

  }

  function runDataTables() {

    /*
     * BASIC
     */
    $('#dt_basic').dataTable({
      "sPaginationType" : "bootstrap_full"
    });

    /* END BASIC */

    /* Add the events etc before DataTables hides a column */
    $("#dt_basic thead input").keyup(function() {
      oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
    });

    $("#dt_basic thead input").each(function(i) {
      this.initVal = this.value;
    });
    $("#datatable_fixed_column thead input").focus(function() {
      if (this.className == "search_init") {
        this.className = "";
        this.value = "";
      }
    });
    $("#dt_basic thead input").blur(function(i) {
      if (this.value == "") {
        this.className = "search_init";
        this.value = this.initVal;
      }
    });   
    

    var oTable = $('#datatable_fixed_column').dataTable({
      "sDom" : "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
      "oLanguage" : {
        "sSearch" : "Search all columns:"
      },
      "bSortCellsTop" : true
    });   
    


    /*
     * COL ORDER
     */
    $('#datatable_col_reorder').dataTable({
      "sPaginationType" : "bootstrap",
      "sDom" : "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "fnInitComplete" : function(oSettings, json) {
        $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
      }
    });
    
    /* END COL ORDER */

    /* TABLE TOOLS */
    $('#datatable_tabletools').dataTable({
      "sDom" : "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "oTableTools" : {
        "aButtons" : ["copy", "print", {
          "sExtends" : "collection",
          "sButtonText" : 'Save <span class="caret" />',
          "aButtons" : ["csv", "xls", "pdf"]
        }],
        "sSwfPath" : "#{ asset_path 'javascript/plugin/datatables/media/swf/copy_csv_xls_pdf.swf'}"
      },
      "fnInitComplete" : function(oSettings, json) {
        $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function() {
          $(this).addClass('btn-sm btn-default');
        });
      }
    });
    
    /* END TABLE TOOLS */

  }

app/views/products_lots/_table.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2 Lotes de Producto
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Producto
            %th Cantidad
            %th Acciones
        %tbody
          - @products_lot.each do |unit|
            %tr
              %td
                = Product.find(unit.product_id).name
              %td 
                = unit.quantity
              %td
                %a.btn.btn-primary.btn-xs{:onclick => "javascript:load_url_ajax('#{lote_by_product_products_lots_path(unit.product_id)}', 'content', null, null, 'GET')"}
                  Ver Lotes del Producto
                %a.btn.btn-primary.btn-xs{:onclick => "javascript:load_url_ajax('#{empty_lots_products_lots_path(unit.product_id)}', 'content', null, null, 'GET')"}
                  Ver Lotes Vácios

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

  // PAGE RELATED SCRIPTS

  loadDataTableScripts();
  function loadDataTableScripts() {

    loadScript("#{ asset_path 'plugin/datatables/jquery.dataTables-cust.min', type: :javascript }", dt_2);

    function dt_2() {
      loadScript("#{ asset_path 'plugin/datatables/ColReorder.min', type: :javascript }", dt_3);
    }

    function dt_3() {
      loadScript("#{ asset_path 'plugin/datatables/FixedColumns.min.js', type: :javascript }", dt_4);
    }

    function dt_4() {
      loadScript("#{ asset_path 'plugin/datatables/ColVis.min', type: :javascript }", dt_5);
    }

    function dt_5() {
      loadScript("#{ asset_path 'plugin/datatables/ZeroClipboard', type: :javascript }", dt_6);
    }

    function dt_6() {
      loadScript("#{ asset_path 'plugin/datatables/media/js/TableTools.min', type: :javascript }", dt_7);
    }

    function dt_7() {
      loadScript("#{ asset_path 'plugin/datatables/DT_bootstrap', type: :javascript }", runDataTables);
    }

  }

  function runDataTables() {

    /*
     * BASIC
     */
    $('#dt_basic').dataTable({
      "sPaginationType" : "bootstrap_full"
    });

    /* END BASIC */

    /* Add the events etc before DataTables hides a column */
    $("#dt_basic thead input").keyup(function() {
      oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
    });

    $("#dt_basic thead input").each(function(i) {
      this.initVal = this.value;
    });
    $("#datatable_fixed_column thead input").focus(function() {
      if (this.className == "search_init") {
        this.className = "";
        this.value = "";
      }
    });
    $("#dt_basic thead input").blur(function(i) {
      if (this.value == "") {
        this.className = "search_init";
        this.value = this.initVal;
      }
    });   
    

    var oTable = $('#datatable_fixed_column').dataTable({
      "sDom" : "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
      "oLanguage" : {
        "sSearch" : "Search all columns:"
      },
      "bSortCellsTop" : true
    });   
    


    /*
     * COL ORDER
     */
    $('#datatable_col_reorder').dataTable({
      "sPaginationType" : "bootstrap",
      "sDom" : "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "fnInitComplete" : function(oSettings, json) {
        $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
      }
    });
    
    /* END COL ORDER */

    /* TABLE TOOLS */
    $('#datatable_tabletools').dataTable({
      "sDom" : "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "oTableTools" : {
        "aButtons" : ["copy", "print", {
          "sExtends" : "collection",
          "sButtonText" : 'Save <span class="caret" />',
          "aButtons" : ["csv", "xls", "pdf"]
        }],
        "sSwfPath" : "#{ asset_path 'javascript/plugin/datatables/media/swf/copy_csv_xls_pdf.swf'}"
      },
      "fnInitComplete" : function(oSettings, json) {
        $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function() {
          $(this).addClass('btn-sm btn-default');
        });
      }
    });
    
    /* END TABLE TOOLS */

  }

app/views/products_lots/edit.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Editar Lote de Producto
  #widget-grid
    .row
      %article.col-sm-12.col-md-12.col-lg-6
        = render :partial => 'form'
        
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left>
    Retornar al listado

:javascript
  $('#backlist-entity').click(function(){
    load_url_ajax("#{products_lots_path}", 'content', null, null, 'GET');
  });

app/views/products_lots/index.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h2.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Productos en el Almacén
      - if flash[:notice] !=nil
        .alert.alert-success.fade.in{"style" => "clear:both"}
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Exito
          = flash[:notice]
      - if flash[:error] != nil
        .alert.alert-danger.fade.in
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Error!
          = flash[:error]
  .row
    .col-md-2
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{new_products_lot_path}', 'content', null, null, 'GET')"}
        Agregar Lote de un Producto
    .col-md-2
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{due_front_products_lots_path}', 'content', null, null, 'POST')"}
        Ver Lotes por Vencer
    .col-md-2
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{lote_front_products_lots_path}', 'content', null, null, 'POST')"}
        Buscar Lotes por producto
  %br
  .row
    #widget-grid 
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        = render :partial => 'table'

app/views/products_lots/new.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Nuevo Lote de Producto
  #widget-grid
    .row
      %article.col-sm-12.col-md-12.col-lg-8
        = render :partial => 'form'
        
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left>
    Retornar al listado

:javascript
  $('#backlist-entity').click(function(){
    load_url_ajax("#{products_lots_path}", 'content', null, null, 'GET');
  });