config/routes.rb
Rails.application.routes.draw do
  resources :products_lots do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
      get 'lote_by_product/:product_id' => 'products_lots#lote_by_product', as: :lote_by_product
      get 'empty_lots/:product_id' => 'products_lots#empty_lots', as: :empty_lots
    end
  end

  resources :businesses

  resources :drivers

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'main#index'
  get 'inbox_task' => 'main#inbox_task', as: :inbox_task_main
  get 'home' => 'main#home'
  post 'home' => 'main#home'

  resources :clients
  resources :drivers
  resources :categories
  resources :suppliers
  resources :products
  resources :transports
  resources :stock_for_articles do
    collection do
      post 'movements'
      post 'due_front'
      post 'due_method'
      post 'lote_front'
      post 'lote_method'
    end
  end
  resources :contracts do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :remission_guides do
    collection do
      post 'add_item'
    end
  end
  resources :purchase_orders do
    collection do
      post 'add_item'
      post 'add_document'
    end
  end
  resources :vouchers do
    collection do
      post 'add_item'
    end
  end

end

app/models/business.rb
class Business < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_one :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :client
  has_many :contract_details
  has_many :contract_documents
  accepts_nested_attributes_for :contract_details, :allow_destroy => true
  accepts_nested_attributes_for :contract_documents, :allow_destroy => true
end

app/models/contract_detail.rb
class ContractDetail < ActiveRecord::Base
  belongs_to :contract
  belongs_to :article
end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_one :products_lot
end

app/models/products_lot.rb
class ProductsLot < ActiveRecord::Base
	belongs_to :product
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
  has_many :purchase_order_details
  has_many :purchase_order_documents
  accepts_nested_attributes_for :purchase_order_details, :allow_destroy => true
  accepts_nested_attributes_for :purchase_order_documents, :allow_destroy => true
end

app/models/remission_guide.rb
class RemissionGuide < ActiveRecord::Base
  belongs_to :client
  has_many :remission_guide_details
  accepts_nested_attributes_for :remission_guide_details, :allow_destroy => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :client
  has_many :voucher_details
  accepts_nested_attributes_for :voucher_details, :allow_destroy => true
end

app/models/voucher_detail.rb
class VoucherDetail < ActiveRecord::Base
  belongs_to :voucher
  belongs_to :article
end

app/controllers/stock_for_articles_controller.rb
class StockForArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new, :create, :edit, :update ]
  protect_from_forgery with: :null_session, :only => [:destroy, :delete]

  def index
    @product = Product.all
    render layout: false
  end

  def due_front
    render(partial: 'due_front', :layout => false)
  end

  def due_method
    limit_date = params[:end_date]
    @products = Product.where("due_date <= ?",limit_date)
    render(partial: 'report_table', :layout => false)
  end

  def lote_front
    @products = Product.all
    render(partial: 'lote_front', :layout => false)
  end

  def lote_method
    article_id = params[:article_id]
    @products = Product.where("id = ?",article_id)
    render(partial: 'report_lote_table', :layout => false)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/stock_for_articles_helper.rb
module StockForArticlesHelper
end

app/views/stock_for_articles/_due_front.haml
#content-inside
  .row
    .col-md-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Producto por Vencer

  .row
    .col-md-12.well
      .input-group
        .col-md-14
          .col-md-10
            %label Fecha Limite
            %input#enddate.string.optional.form-control{'name'=>'end_date', type: "date"}
          %br
          .col-md-2
            %button#show-table.btn.btn-primary.btn-default{:type => 'button'}
              %i.fa.fa-search
              Buscar
    %br
      .row
        #widget-grid
          .col-xs-1.col-sm-1.col-md-1.col-lg-1
          %article.col-xs-10.col-sm-10.col-md-10.col-lg-10
            #table-information-result
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left
    Retornar al listado

:javascript
  $(document).ready(function (){
    $('select').select2({width:'280px'});
  });

  $('#show-table').click(function(){
    var end_date = $('#enddate').val();

    if(end_date != 0) {
      var parameters = { end_date: end_date, authenticity_token: "#{form_authenticity_token}" };
      load_items_delivery_order_ajax("#{due_method_stock_for_articles_path}", 'table-information-result', parameters);
    } else {
      alert('Por favor, especificar todos los datos necesarios.')
    }
  });


  $('#backlist-entity').click(function(){
    load_url_ajax("#{stock_for_articles_path}", 'content', null, null, 'GET');
  });

app/views/stock_for_articles/_lote_front.haml
#content-inside
  .row
    .col-md-12.col-sm-7.col-md-7.col-lg-4
      %h1.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Producto por Vencer

  .row
    .col-md-12.well
      .input-group
        .col-md-14
          .col-md-10
            .row{ :style => "margin-top:5%;"}
              %section.col.col-md-12
                %select.form-control#article-select{:name =>"article_id", :required => false}
                  %option{:value => "", :rel => ""}
                    Seleccione
                  - @products.each do |x|
                    %option{:value => "#{x.id}"}
                      = x.name.to_s
          %br
          .col-md-2
            %button#show-table.btn.btn-primary.btn-default{:type => 'button'}
              %i.fa.fa-search
              Buscar
    %br
      .row
        #widget-grid
          .col-xs-1.col-sm-1.col-md-1.col-lg-1
          %article.col-xs-10.col-sm-10.col-md-10.col-lg-10
            #table-information-result
  %button.btn.btn-sm.btn-primary.btn-prev#backlist-entity{type: "button"}
    %i.fa.fa-arrow-left
    Retornar al listado

:javascript
  $(document).ready(function (){
    $('select').select2({width:'280px'});
  });

  $('#show-table').click(function(){
    var article = $('#article-select').val();

    if(article != 0) {
      var parameters = { article_id: article, authenticity_token: "#{form_authenticity_token}" };
      load_items_delivery_order_ajax("#{lote_method_stock_for_articles_path}", 'table-information-result', parameters);
    } else {
      alert('Por favor, especificar todos los datos necesarios.')
    }
  });


  $('#backlist-entity').click(function(){
    load_url_ajax("#{stock_for_articles_path}", 'content', null, null, 'GET');
  });

app/views/stock_for_articles/_report_lote_table.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2
      = "Productos por vencer"
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{"style"=>"text-align:center"} Articulo
            %th{"style"=>"text-align:center"} Cantidad
            %th{"style"=>"text-align:center"} Fecha de Vencimiento
            %th{"style"=>"text-align:center"} Lote
        %tbody
          - @products.each do |unit|
            %tr
              %td{"style"=>"text-align:center"}
                = unit.name
              %td{"style"=>"text-align:center"}
                = unit.quantity.to_s
              %td{"style"=>"text-align:center"}
                = unit.due_date.to_s
              %td{"style"=>"text-align:center"}
                = unit.lot_number.to_s

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

app/views/stock_for_articles/_report_table.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2
      = "Productos por vencer"
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{"style"=>"text-align:center"} Articulo
            %th{"style"=>"text-align:center"} Cantidad
            %th{"style"=>"text-align:center"} Fecha de Vencimiento
            %th{"style"=>"text-align:center"} Lote
        %tbody
          - @products.each do |unit|
            %tr
              %td{"style"=>"text-align:center"}
                = unit.name
              %td{"style"=>"text-align:center"}
                = unit.quantity.to_s
              %td{"style"=>"text-align:center"}
                = unit.due_date.to_s
              %td{"style"=>"text-align:center"}
                = unit.lot_number.to_s

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

app/views/stock_for_articles/_table.haml
#wid-id-0.jarviswidget.jarviswidget-color-darken{"data-widget-editbutton" => "false"}
  %header
    %span.widget-icon
      %i.fa.fa-table
    %h2 Articulos
  %div
    .jarviswidget-editbox
    .widget-body.no-padding
      .widget-body-toolbar
      %table#dt_basic.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th #
            %th Nombre
            %th Marca
            %th Unidad de Medida
            %th Cantidad
            %th Número de Lote
            %th Registro Sanitario
            %th Fecha de Producción
            %th Fecha de Vencimiento
            %th Acciones
        %tbody
          - @product.each do |unit|
            %tr
              %td 
                = unit.id
              %td 
                = unit.name
              %td
                = unit.trademark
              %td
                = unit.unit_of_measurement
              %td
                = unit.quantity
              %td
                = unit.lot_number
              %td
                = unit.sanitary_registry
              %td
                = unit.production_date
              %td
                = unit.due_date
              %td
                %a.btn.btn-info.btn-xs{:onclick => "javascript:load_url_ajax('#{edit_product_path(unit.id)}', 'content', null, null, 'GET')"}
                  Entradas y Salidas

:javascript
  // DO NOT REMOVE : GLOBAL FUNCTIONS!
  pageSetUp();

  $(document).ready(function () {
    $('[data-toggle="confirmation"]').confirmation();
  });

  // PAGE RELATED SCRIPTS

  loadDataTableScripts();
  function loadDataTableScripts() {

    loadScript("#{ asset_path 'plugin/datatables/jquery.dataTables-cust.min', type: :javascript }", dt_2);

    function dt_2() {
      loadScript("#{ asset_path 'plugin/datatables/ColReorder.min', type: :javascript }", dt_3);
    }

    function dt_3() {
      loadScript("#{ asset_path 'plugin/datatables/FixedColumns.min.js', type: :javascript }", dt_4);
    }

    function dt_4() {
      loadScript("#{ asset_path 'plugin/datatables/ColVis.min', type: :javascript }", dt_5);
    }

    function dt_5() {
      loadScript("#{ asset_path 'plugin/datatables/ZeroClipboard', type: :javascript }", dt_6);
    }

    function dt_6() {
      loadScript("#{ asset_path 'plugin/datatables/media/js/TableTools.min', type: :javascript }", dt_7);
    }

    function dt_7() {
      loadScript("#{ asset_path 'plugin/datatables/DT_bootstrap', type: :javascript }", runDataTables);
    }

  }

  function runDataTables() {

    /*
     * BASIC
     */
    $('#dt_basic').dataTable({
      "sPaginationType" : "bootstrap_full"
    });

    /* END BASIC */

    /* Add the events etc before DataTables hides a column */
    $("#dt_basic thead input").keyup(function() {
      oTable.fnFilter(this.value, oTable.oApi._fnVisibleToColumnIndex(oTable.fnSettings(), $("thead input").index(this)));
    });

    $("#dt_basic thead input").each(function(i) {
      this.initVal = this.value;
    });
    $("#datatable_fixed_column thead input").focus(function() {
      if (this.className == "search_init") {
        this.className = "";
        this.value = "";
      }
    });
    $("#dt_basic thead input").blur(function(i) {
      if (this.value == "") {
        this.className = "search_init";
        this.value = this.initVal;
      }
    });   
    

    var oTable = $('#datatable_fixed_column').dataTable({
      "sDom" : "<'dt-top-row'><'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      //"sDom" : "t<'row dt-wrapper'<'col-sm-6'i><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'>>",
      "oLanguage" : {
        "sSearch" : "Search all columns:"
      },
      "bSortCellsTop" : true
    });   
    


    /*
     * COL ORDER
     */
    $('#datatable_col_reorder').dataTable({
      "sPaginationType" : "bootstrap",
      "sDom" : "R<'dt-top-row'Clf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "fnInitComplete" : function(oSettings, json) {
        $('.ColVis_Button').addClass('btn btn-default btn-sm').html('Columns <i class="icon-arrow-down"></i>');
      }
    });
    
    /* END COL ORDER */

    /* TABLE TOOLS */
    $('#datatable_tabletools').dataTable({
      "sDom" : "<'dt-top-row'Tlf>r<'dt-wrapper't><'dt-row dt-bottom-row'<'row'<'col-sm-6'i><'col-sm-6 text-right'p>>",
      "oTableTools" : {
        "aButtons" : ["copy", "print", {
          "sExtends" : "collection",
          "sButtonText" : 'Save <span class="caret" />',
          "aButtons" : ["csv", "xls", "pdf"]
        }],
        "sSwfPath" : "#{ asset_path 'javascript/plugin/datatables/media/swf/copy_csv_xls_pdf.swf'}"
      },
      "fnInitComplete" : function(oSettings, json) {
        $(this).closest('#dt_table_tools_wrapper').find('.DTTT.btn-group').addClass('table_tools_group').children('a.btn').each(function() {
          $(this).addClass('btn-sm btn-default');
        });
      }
    });
    
    /* END TABLE TOOLS */

  }

app/views/stock_for_articles/index.html.haml
#content-inside
  .row
    .col-xs-12.col-sm-7.col-md-7.col-lg-4
      %h2.page-title.txt-color-blueDark
        %i.fa.fa-pencil-square-o.fa-fw 
        Productos en el Almacén
      - if flash[:notice] !=nil
        .alert.alert-success.fade.in{"style" => "clear:both"}
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Exito
          = flash[:notice]
      - if flash[:error] != nil
        .alert.alert-danger.fade.in
          %button.close{"data-dismiss" => "alert"}
            x
          %i.fa-fw.fa.fa-check
          %strong Error!
          = flash[:error]
  .row
    .col-md-2
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{due_front_stock_for_articles_path}', 'content', null, null, 'POST')"}
        Lotes por Vencer
    .col-md-2
      %button.btn.btn-primary.btn-mini{:onclick => "javascript:load_url_ajax('#{lote_front_stock_for_articles_path}', 'content', null, null, 'POST')"}
        Lotes por producto

  %br
  .row
    #widget-grid 
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        = render :partial => 'table'